# Generated by Django 4.1.7 on 2023-03-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_origin', models.CharField(max_length=67)),
                ('flight_destination', models.CharField(max_length=67)),
                ('flight_duration', models.IntegerField()),
            ],
        ),
    ]
